plugins:
  - tmuxp_plugin_loader.plugin.Loader
# shell_command_before:
# - >
#   [ -d `.venv/bin/activate` ] &&
#   source .venv/bin/activate &&
#   reset
# - sleep 1
# environment:
#   EDITOR: /usr/bin/vim
# global_options:
#   default-shell: /bin/sh
#   default-command: /bin/sh
# options:
#   main-pane-height: ${MAIN_PANE_HEIGHT}
options:
  automatic-rename: on
synchronize-panes: on

windows:
  - window_name: editor
    # options:
    #   automatic-rename: on
    #   main-pane-height: 30
    start_directory: .
    layout: even-horizontal
    panes:
      - shell_command:
        - editor .
    # options_after:
    # synchronize-panes: on

  - window_name: shell
    start_directory: .
    layout: even-horizontal
    panes:
      - pane
